version: "3.2"

services:
  nginx:
    build:
      dockerfile: Dockerfile.production
      args:
        environment: production
    volumes:
      - ./dashboard/dist:/dashboard
      - ./game-client/dist:/client
      - ./game-stats/dist:/stats
      - ./game-challenge/button/dist:/button
      - ./game-challenge/clicker/dist:/clicker
      - ./game-challenge/graph/dist:/graph
      - ./game-challenge/hidden/dist:/hidden
      - ./game-challenge/quiz/dist:/quiz
      - ./game-challenge/skill/dist:/skill
      - ./game-challenge/sorting/dist:/sorting
      - ./game-challenge/astragal/dist:/astragal

  cms-frontend:
    build:
      dockerfile: Dockerfile.production
    environment:
      PORT: 80

  mongo:
    ports:
      - "27017:27017"

  game-server:
    build:
      dockerfile: Dockerfile.production

  mongo-access:
    build:
      dockerfile: Dockerfile.production
