version: "3.2"

services:
  nginx:
    build:
      args:
        environment: development
    depends_on:
      - game-client

  cms-frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  dashboard:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./dashboard:/app
      - /app/node_modules

  game-client:
    build:
      context: ./game-client
      dockerfile: Dockerfile.development
    environment:
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
      PORT: 443
    depends_on:
      - content-server
      - asset-server
      - game-server
      - game-challenge-button
      - game-challenge-quiz
      - game-challenge-clicker
      - game-challenge-hidden
      - game-challenge-skill
      - game-challenge-graph
      - game-challenge-sorting
    volumes:
      - ./game-client:/app
      - /app/node_modules


  dashboard:
    build:
      context: ./dashboard
    environment:
      CONTENT_SERVER_URI: https://content-server.${HOST}
      ASSET_SERVER_URI: https://asset-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      FONT_URI: https://static.${HOST}/fonts
      PORT: 443
    depends_on:
      - content-server
      - asset-server
      - game-server

  game-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-server:/app
      - /app/node_modules

  mongo:
    ports:
      - "27017:27017"

  game-challenge-button:
    build:
      context: ./game-challenge/button
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
    volumes:
      - ./game-challenge/button:/app
      - /app/node_modules

  game-challenge-sorting:
    build:
      context: ./game-challenge/sorting
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/sorting:/app
      - /app/node_modules

  game-challenge-quiz:
    build:
      context: ./game-challenge/quiz
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/quiz:/app
      - /app/node_modules

  game-challenge-clicker:
    build:
      context: ./game-challenge/clicker
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/clicker:/app
      - /app/node_modules

  game-challenge-graph:
    build:
      context: ./game-challenge/graph
      dockerfile: Dockerfile.development
    environment:
      PORT: 80
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/graph:/app
      - /app/node_modules

  game-challenge-hidden:
    build:
      context: ./game-challenge/hidden
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/hidden:/app
      - /app/node_modules

  game-challenge-skill:
    build:
      context: ./game-challenge/skill
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      GAME_SERVER_URI: https://game-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/skill:/app
      - /app/node_modules
