version: "3.2"

services:
  nginx:
    build:
      dockerfile: Dockerfile.production
      args:
        environment: production
    volumes:
      - ./game-client/dist:/client
      - ./game-challenge/button/dist:/button
      - ./game-challenge/clicker/dist:/clicker
      - ./game-challenge/graph/dist:/graph
      - ./game-challenge/hidden/dist:/hidden
      - ./game-challenge/quiz/dist:/quiz
      - ./game-challenge/skill/dist:/skill
      - ./game-challenge/sorting/dist:/sorting

  cms-frontend:
    build:
      dockerfile: Dockerfile.production
    environment:
      PORT: 80

  mongo:
    ports:
      - "27017:27017"

  dashboard:
    build:
      dockerfile: Dockerfile.production

  game-server:
    build:
      dockerfile: Dockerfile.production
