version: "3.2"

services:
  nginx:
    build:
      args:
        environment: development

  cms-frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  dashboard:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./dashboard:/app
      - /app/node_modules

  game-client:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-client:/app
      - /app/node_modules

  game-server:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-server:/app
      - /app/node_modules

  mongo:
    ports:
      - "27017:27017"

  game-challenge-button:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/button:/app
      - /app/node_modules

   game-challenge-sorting:
     build:
       dockerfile: Dockerfile.development
     volumes:
       - ./game-challenge/sorting:/app
       - /app/node_modules
     ports:
       - 8080:80

  game-challenge-quiz:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/quiz:/app
      - /app/node_modules

  game-challenge-clicker:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/clicker:/app
      - /app/node_modules

  game-challenge-graph:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/graph:/app
      - /app/node_modules

  game-challenge-hidden:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/hidden:/app
      - /app/node_modules

  game-challenge-skill:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./game-challenge/skill:/app
      - /app/node_modules
