version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - asset-server
      - content-server
      - content-repo
      - game-server
      - mongo-access
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./assets:/html
      - ./cms-frontend/public:/cms-frontend
      - ./dashboard/dist:/dashboard
      - ./game-client/dist:/client
      - ./game-stats/dist:/stats
      - ./game-challenge/button/dist:/button
      - ./game-challenge/clicker/dist:/clicker
      - ./game-challenge/graph/dist:/graph
      - ./game-challenge/hidden/dist:/hidden
      - ./game-challenge/quiz/dist:/quiz
      - ./game-challenge/skill/dist:/skill
      - ./game-challenge/sorting/dist:/sorting
      - ${CERTIFICATE_PATH}:/certificate

  asset-server:
    build: ./asset-server
    volumes:
      - type: volume
        source: assets
        target: /var/www/webdav

  content-server:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://content-repo/
      BODY_SIZE_LIMIT: "1mb"
      PORT: 80
    depends_on:
      - content-repo

  content-repo:
    build: ./content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content

  game-server:
    build:
      context: ./game-server
    environment:
      MONGODB_URI: mongodb://mongo
    depends_on:
      - mongo

  mongo:
    image: "mongo:3.6.3-jessie"
    volumes:
      - type: volume
        source: mongoDB
        target: /data/db
    ports:
      - "27017:27017"

  mongo-access:
      build:
        context: ./mongo-access
      environment:
        MONGODB_URI: mongodb://mongo
      depends_on:
        - mongo

volumes:
  content:
  assets:
  mongoDB:
