version: "3.2"

services:
  nginx:
    build:
      dockerfile: Dockerfile.production
      args:
        environment: production
    volumes:
      - ./game-client/dist:/client
      - ./game-challenge/clicker/dist:/clicker
      - ./game-challenge/hidden/dist:/hidden
      - ./game-challenge/quiz/dist:/quiz
      - ./game-challenge/sorting/dist:/sorting

  cms-frontend:
    build:
      dockerfile: Dockerfile.production
    environment:
      GIT_JSON_API_URI: https://content-server.${HOST}
      ASSET_SERVER_URI: https://asset-server.${HOST}
      BASIC_AUTH_USER:
      BASIC_AUTH_PASSWORD:
      PORT: 80

  game-challenge-tracker:
    build:
      dockerfile: Dockerfile.production
