version: "3.2"

services:
  nginx:
    build:
      args:
        environment: development
    depends_on:
      - game-client

  cms-frontend:
    build:
      dockerfile: Dockerfile.development
    volumes:
      - ./cms-frontend:/app
      - /app/node_modules
    environment:
      PORT: 443

  game-client:
    build:
      context: ./game-client
      dockerfile: Dockerfile.development
    environment:
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
      PORT: 443
    depends_on:
      - content-server
      - asset-server
      - game-challenge-quiz
      - game-challenge-clicker
      - game-challenge-hidden
      - game-challenge-sorting
    volumes:
      - ./game-client:/app

  game-challenge-sorting:
    build:
      context: ./game-challenge/sorting
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/sorting:/app
      - /app/node_modules

  game-challenge-quiz:
    build:
      context: ./game-challenge/quiz
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/quiz:/app
      - /app/node_modules

  game-challenge-clicker:
    build:
      context: ./game-challenge/clicker
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/clicker:/app
      - /app/node_modules

  game-challenge-hidden:
    build:
      context: ./game-challenge/hidden
      dockerfile: Dockerfile.development
    environment:
      PORT: 443
      ASSET_SERVER_URI: https://asset-server.${HOST}
      CONTENT_SERVER_URI: https://content-server.${HOST}
      STATIC_SERVER_URI: https://static.${HOST}
    volumes:
      - ./game-challenge/hidden:/app
      - /app/node_modules

  game-challenge-tracker:
    build:
      dockerfile: Dockerfile.development
    volumes:
        - ./game-challenge-tracker:/app
