version: "3.2"

services:
  nginx:
    build: ./nginx
    depends_on:
      - asset-server
      - content-server
      - content-repo
      - cms-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/certificate
      - ./assets:/html

  asset-server:
    build: ./asset-server
    volumes:
      - ./assets:/var/www/webdav

  content-server:
    image: "artcom/git-json-api:latest"
    environment:
      REPO_URI: http://content-repo/
      BODY_SIZE_LIMIT: "1mb"
      PORT: 80
    depends_on:
      - content-repo

  content-repo:
    build: ./content-repo
    volumes:
      - type: volume
        source: content
        target: /srv/content

  cms-frontend:
    build:
      context: ./cms-frontend
    environment:
      GIT_JSON_API_URI: https://content-server.${HOST}
      ASSET_SERVER_URI: https://asset-server.${HOST}
    depends_on:
      - content-server
      - asset-server

volumes:
  content:
